name: actions
on: 
  push:
    branches:
        - master
        - feature/**
        - '!feature/featC'
    tags:
        - v[12].[0-9]+.[0-9]+
    paths:
        - '**.js?'
jobs:
    run-github-actions:
        runs-on: ubuntu-latest
        steps:
          - name: List files
            run: |
                pwd
                ls -a
          - name: Checkout
            uses: actions/checkout@v1
          - name: List files after checkout
            run: |
                pwd
                ls -a  
          - name: hello-world
            id: helloworld
            uses: actions/hello-world-docker-action@v1
            with: 
              who-to-greet: César
          - name: hello-world-output
            run: echo "${{steps.helloworld.outputs.time}}"
    create_issue:
        runs-on: ubuntu-latest
        steps:
        - name: Create issue using REST API
          run: |
            curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/issues \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
              "title": "Automated issue for commit: ${{ github.sha }}",
              "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
               }'
    
            