name: actions

on: [push]

jobs:
    run-github-actions:
        runs-on: ubuntu-latest
        steps:
          - name: List files
            run: |
                pwd
                ls -a
          - name: Checkout
            uses: actions/checkout@v1
          - name: List files after checkout
            run: |
                pwd
                ls -a  
          - name: hello-world
            id: helloworld
            uses: actions/hello-world-docker-action@v1
            with: 
              who-to-greet: César
          - name: hello-world-output
            run: echo "${{steps.helloworld.outputs.time}}"
            