name: Container

on: push

jobs:
    node-docker:
        runs-on: ubuntu-latest
        container:
            image: node:13.14.0-alpine3.10
        steps: 
            - name: log node version
              run: |
                  node -v
                  cat /etc/os-release
    github-vm:
        runs-on: ubuntu-latest
        steps: 
            - name: log node version
              run: |
                  node -v
                  cat /etc/os-release


